accounts/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth.views import (
    login, logout, password_reset, password_reset_done, password_reset_confirm,
    password_reset_complete
)

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^login/$', login, {'template_name': 'accounts/login.html'}, name='login'),
    url(r'^logout/$', logout, {'template_name': 'accounts/logout.html'}, name='logout'),
    url(r'^register/$', views.register, name='register'),
    url(r'^profile/$', views.profile, name='profile'),
    url(r'^profile/edit$', views.edit_profile, name='edit_profile'),
    url(r'^change-password$', views.change_password, name='change_password'),
    url(r'^reset-password/$', password_reset, {'template_name': 'accounts/reset_password.html', 'post_reset_redirect': 'accounts:password_reset_done', 'email_template_name': 'accounts/reset_password_email.html'}, name='reset_password'),
    url(r'^reset-password/done/$', password_reset_done, {'template_name': 'accounts/reset_password_done.html'}, name='password_reset_done'),
    url(r'^reset-password/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', password_reset_confirm, {'template_name': 'accounts/reset_password_confirm.html', 'post_reset_redirect': 'accounts:password_reset_complete'}, name='password_reset_confirm'),
    url(r'^reset-password/complete/$', password_reset_complete,{'template_name': 'accounts/reset_password_complete.html'}, name='password_reset_complete')

]

login/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from login import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^$', views.login_redirect, name='login_redirect'),
    url(r'^admin/', admin.site.urls),
    url(r'^account/', include('accounts.urls', namespace='accounts')),
]

accounts/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.contrib.auth.models import AbstractUser, UserManager

from django.db import models, migrations
from django.contrib.auth.models import User, AbstractUser, UserManager
from django.db.models.signals import post_save
from django.dispatch import receiver
import psycopg2

# Create your models here.
class UserProfile(models.Model):
    user = models.OneToOneField(User, primary_key=True)
    phone = models.CharField(max_length=10, default='')
    hint = models.CharField(max_length=100, default='')

    def __str__(self):
        return self.user.username

def create_profile(sender, **kwargs):
    if kwargs['created']:
        user_profile = UserProfile.objects.create(user=kwargs['instance'])

post_save.connect(create_profile, sender=User)

accounts/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.utils.translation import gettext_lazy as _
from accounts.models import UserProfile
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
import psycopg2



class RegistrationForm(UserCreationForm):
    email = forms.EmailField(required=True)
    phone = forms.CharField(required=True)
    hint = forms.CharField(required=True)
    class Meta():
        model = User
        fields = (
            'username',
            'first_name',
            'last_name',
            'email',
            'password1',
            'password2',
            'phone',
            'hint'

        )

    def save(self, commit=True):
        user = super(RegistrationForm, self).save(commit=False)
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        user.email = self.cleaned_data['email']
        user.phone = self.cleaned_data['phone']
        user.hint = self.cleaned_data['hint']

        if commit:
            user.save()

        return user

class EditProfileForm(UserChangeForm):
    email = forms.EmailField(required=True)
    phone = forms.CharField(required=True)
    hint = forms.CharField(required=True)
    class Meta:
        model = User
        fields = (
            'email',
            'first_name',
            'last_name',
            'password',
            'phone',
            'hint'
        )

accounts/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
import psycopg2
from django.shortcuts import render, redirect
from accounts.models import UserProfile
from accounts.forms import (
     RegistrationForm,
     EditProfileForm
 )
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserChangeForm, PasswordChangeForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth import update_session_auth_hash
from django.urls import reverse

# Create your views here.

def home(request):
    return render(request, 'accounts/home.html')

def register(request):
    if request.method == 'POST':
        user_form = RegistrationForm(data=request.POST)
        if user_form.is_valid():
            user = user_form.save()
            user.refresh_from_db()
            user.hint = user_form.cleaned_data.get('hint')
            user.phone = user_form.cleaned_data.get('phone')
            user.save()
            raw_password = user_form.cleaned_data.get('password1')
            user = authenticate(username=user.username, password=raw_password)
            login(request, user)
            return redirect(reverse('accounts:home'))
    else:
        user_form = RegistrationForm()
    return render(request,'accounts/reg_form.html',
                          {'user_form':user_form})


def profile(request):
    args ={'user': request.user}
    return render(request, 'accounts/profile.html', args)

def edit_profile(request):
    if request.method =='POST':
        form = EditProfileForm(request.POST, instance=request.user)

        if form.is_valid():
            form.save()
            return redirect('accounts:profile')
    else:
        form = EditProfileForm(instance=request.user)
        args = {'form': form}
        return render(request, 'accounts/edit_profile.html', args)

def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(data=request.POST, user=request.user)

        if form.is_valid:
            form.save()
            update_session_auth_hash(request, form.user)
            return redirect('accounts:profile')
        else:
            return redirect('accounts:change-password')

    else:
        form = PasswordChangeForm(user=request.user)

        args = {'form': form}
        return render(request, 'accounts/change_password.html', args)

login/views.py
from django.shortcuts import redirect

def login_redirect(request):
    return redirect('/account/login')

accounts/templates/accounts/change_password.html
{% extends 'base.html' %}


    {% block head %}
    <title>Profile</title>
    {% endblock %}

    {% block body %}
    <div class="container">
      <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Submit</button>
      </form>
      <br>
    </div>

  {% endblock %}

accounts/templates/accounts/edit_profile.html
{% extends 'base.html' %}


    {% block head %}
    <title>Profile</title>
    {% endblock %}

    {% block body %}
    <div class="container">
      <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Submit</button>
      </form>
      <br>
    </div>

  {% endblock %}

accounts/templates/accounts/home.html
{% extends 'base.html' %}
<h1>Home page</h1>
<!DOCTYPE html>
    {% block head %}
    <title>Home</title>
    {% endblock %}

    {% block body %}
    <h1>Welcome Home!</h1>
    <h3>Checkout Your Profile By Clicking One Of The Tabs Above</h3>
    {% endblock %}

accounts/templates/accounts/login.html
<body>
  {% extends 'base.html' %}

{% block body %}
<div class="container">
  <h1>Welcome</h1>
  <p>
    You can log in here
  </p>
  <h2>Login</h2>
  <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit" name="button">Login</button>
  </form>
  <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal">
    Forgot Password
  </button>

  <!-- The Modal -->
  <div class="modal" id="myModal">
    <div class="modal-dialog">
      <div class="modal-content">

        <!-- Modal Header -->
        <div class="modal-header">
          <h4 class="modal-title">Forgot Your Password?</h4>
          <button type="button" class="close" data-dismiss="modal">&times;</button>
        </div>

        <!-- Modal body -->
        <div class="modal-body">
          <p>You can reset your password by using the 'Reset Paswword' link above</p>
        </div>

        <!-- Modal footer -->
        <div class="modal-footer">
          <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
        </div>

      </div>
    </div>
  </div>
</div>
{% endblock %}
</body>

accounts/templates/accounts/logout.html
{% extends 'base.html' %}

{% block body %}
<div class="container">
  <h1>Logged out!</h1>
  <p>
    You have logged out
  </p>
</div>
{% endblock %}

accounts/templates/accounts/profile.html
{% extends 'base.html' %}


    {% block head %}
    <title>Profile</title>
    {% endblock %}

    {% block body %}
    <div class="container">
      <h1>Profile</h1>
      <p>Username: {{ user }}</p>
      <p>First Name: {{ user.first_name }}</p>
      <p>Last name: {{ user.last_name }}</p>
      <p>Email: {{ user.email }}</p>
      <p>Phone: {{ user.userprofile.phone }}</p>
      <p>Hint: {{ user.userprofile.hint }}</p>
      <p>Last Login: {{ user.last_login }}</p>
    </div>

    {% endblock %}

accounts/templates/accounts/reg_form.html
{% extends 'base.html' %}

{% block body %}
<div class="container">
  <h1>Register</h1>
<form method="post">
    {% csrf_token %}
    {{ user_form.as_p }}
    <button type="submit" name="button">Submit</button>
</form>
</div>
{% endblock %}

accounts/templates/accounts/reset_password.html
{% extends 'base.html' %}

{% block body %}
<div class="container">
    <h1>Password reset</h1>
    <p>
        Forgotten your password? Enter your email address below, and we'll email instructions for setting a new one.
    </p>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Reset password</button>
    </form>
</div>
{% endblock %}

accounts/templates/accounts/reset_password_complete.html
{% extends 'base.html' %}

{% block body %}
<div class="container">
    <h1>Password reset complete</h1>
    <a href="{% url 'accounts:login' %}">Log in</a>
</div>
{% endblock %}

accounts/templates/accounts/reset_password_confirm.html
{% extends 'base.html' %}

{% block body %}
<div class="container">
    <h1>Enter new password</h1>
    <p>

    </p>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Reset password</button>
    </form>
</div>
{% endblock %}

accounts/templates/accounts/reset_password_done.html
{% extends 'base.html' %}

{% block body %}
<div class="container">
    <h1>Password reset sent</h1>
    <p>
        We've emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly.

        If you don't receive an email, please make sure you've entered the address you registered with, and check your spam folder.
    </p>
</div>
{% endblock %}

accounts/templates/accounts/reset_password_email.html
{% load i18n %}{% autoescape off %}
{% blocktrans %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktrans %}

{% trans "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'accounts:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% trans "Your username, in case you've forgotten:" %} {{ user.get_username }}

{% trans "Thanks for using our site!" %}

{% blocktrans %}The {{ site_name }} team{% endblocktrans %}

{% endautoescape %}

accounts/templates/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    {% block head %}
    <meta charset="utf-8">
    <title>Base</title>
    {% endblock %}
  </head>
  <body>
    <br>
    <div class="container">
    <nav class="navbar navbar-expand-lg navbar-light bg-light rounded">
      <a class="navbar-brand" href="/">Login Challenge</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample09" aria-controls="navbarsExample09" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarsExample09">
         <ul class="navbar-nav mr-auto">
           <li class="nav-item active">
        {% if user.is_authenticated %}
        <ul class="nav navbar-nav">
            <li><a class="nav-link" href="{% url 'accounts:home' %}">Home</a></li>
            <li><a class="nav-link" href="{% url 'accounts:profile' %}">Profile</a></li>
            <li><a class="nav-link" href="{% url 'accounts:edit_profile' %}">Edit Profile</a></li>
            <li><a class="nav-link" href="{% url 'accounts:change_password' %}">Change Password</a></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
            <li><a class="nav-link" href="{% url 'accounts:logout' %}">Log out</a></li>
        </ul>
        {% else %}
        <ul class="nav navbar-nav">
            <li><a class="nav-link" href="{% url 'accounts:reset_password' %}">Reset Password</a></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
            <li><a class="nav-link" href="{% url 'accounts:login' %}">Login</a></li>
            <li><a class="nav-link" href="{% url 'accounts:register' %}">Register</a></li>
        </ul>
        {% endif %}
      </div>
    </nav>
    {% block body %}
    {% endblock %}
  </body>
</html>